### ISSUE TITLE
Babylon bbn-test-2

### ISSUE THREAD

**Issue by mmiki76** [node101-io/klein#8]
Activating 
vbash: line 
![Klein-Babylon node](https://github.com/node101-io/klein/assets/159566019/a12b1f06-582d-4c5d-971d-1e61901a8b1c)
1: babylond: command not found:

the node does not synchronize and does not start

**Comment by necipsagiro** [comment]
Hi, this usually happens when installation process is interrupted by external factors. Deleting the node and reinstalling should solve the problem.
