### ISSUE TITLE
Babylon testnet node

### ISSUE THREAD

**Issue by lpierce06** [node101-io/klein#9]
trying to use add validator feature, filled in all but optional entries, got error below

Syntax error: unexpected end of JSON input

**Comment by sandymac189** [comment]
trying to do node101 section and keep getting error message.
Syntax error: unexpected end of JSON input
I have another node and tried it on that with the other address and so far it has been on tthe blocks pic on klein for about 15 mins.
thanks.

**Comment by necipsagiro** [comment]
Hey @lpierce06, have you created a BLS key before adding a validator?

**Comment by sandymac189** [comment]
Hi. Yes.

There were instructions on (node instructions) on klein.
I logged in to my other node and delegated to node101 and went through the motions and it went straight through,I just put my second wallet name in. (Send wallet)
Hoping that’s the issue resolved,waiting for it to appear in inactive

**Comment by necipsagiro** [comment]
Glas to hear that, I'm closing this issue for now. Feel free to reopen it if you encounter any problems.

**Comment by sandymac189** [comment]
Thank you for your time and help
